

#BSUB -P atac_seq
#BSUB -o atac_seq_yli11_2020-06-11.BWA.message_%J_%I.out -e atac_seq_yli11_2020-06-11.BWA.message_%J_%I.err
#BSUB -n 6
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "BWA[1-1]"
module purge
#BSUB -w "ended(105192413[*])"
module load bwa/0.7.16a
module load samtools/1.7

id=$LSB_JOBINDEX
COL1=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id atac_seq_yli11_2020-06-11.bwa.input|tail -n1`

bwa mem -t 6 /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../mm9/bwa_16a_index/mm9.fa ${COL1} ${COL2} |samtools view -@ 6 -bS - > ${COL3}.bam
rm ${COL1}
rm ${COL2}

		