

#BSUB -P atac_seq
#BSUB -o atac_seq_yli11_2020-06-11.rmdup.bw.message_%J_%I.out -e atac_seq_yli11_2020-06-11.rmdup.bw.message_%J_%I.err
#BSUB -n 6
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4500]"
#BSUB -J "rmdup.bw[1-1]"
module purge
#BSUB -w "ended(105192415[*])"
#BSUB -R "select[rhel7]"
module load python/2.7.15-rhel7

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

bamCoverage -b ${COL3}.rmdup.bam -o ${COL3}.rmdup.bw --smoothLength=200 --ignoreForNormalization chrX chrM   --effectiveGenomeSize 1865500000 --numberOfProcessors 6 --centerReads

		