

#BSUB -P atac_seq
#BSUB -o atac_seq_yli11_2020-06-11.tracks.message_%J_%I.out -e atac_seq_yli11_2020-06-11.tracks.message_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=2000]"
#BSUB -J "tracks[1-1]"
module purge
#BSUB -w "ended(105192413) && ended(105192412) && ended(105192415) && ended(105192414) && ended(105192420) && ended(105192418) && ended(105192421) && ended(105192419) && ended(105192416)"
module load python/2.7.13

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/upload_tracks.py cd01f29076b0 HPC5_ATAC.markdup.rmchrM_treat_pvalue.bw,HPC5_ATAC.rmdup_treat_pvalue.bw,HPC5_ATAC.rmdup.uq.rmchrM_treat_pvalue.bw treat_pvalue.bw mm9
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/upload_tracks.py c70ba8139cc5 HPC5_ATAC.rmdup.bw rmdup.bw mm9
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/upload_tracks.py 145f70331427 HPC5_ATAC.rmdup.uq.bw rmdup.uq.bw mm9
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/upload_tracks.py 6a6dba74aae6 HPC5_ATAC.markdup.rmchrM_FE.bw,HPC5_ATAC.rmdup_FE.bw,HPC5_ATAC.rmdup.uq.rmchrM_FE.bw FE.bw mm9
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/upload_tracks.py dec6be54a02e HPC5_ATAC.all.bw all.bw mm9
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/upload_tracks.py a95d5bb12416 HPC5_ATAC.markdup.rmchrM_logLR.bw,HPC5_ATAC.rmdup_logLR.bw,HPC5_ATAC.rmdup.uq.rmchrM_logLR.bw logLR.bw mm9

		