

#BSUB -P atac_seq
#BSUB -o atac_seq_yli11_2020-06-11.skewer.message_%J_%I.out -e atac_seq_yli11_2020-06-11.skewer.message_%J_%I.err
#BSUB -n 4
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "trim[1-1]"
module purge


id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/skewer-0.2.2-linux-x86_64 -t 4 -x CTGTCTCTTATACACATCT -y CTGTCTCTTATACACATCT ${COL1} 		${COL2} -z yes -o ${COL3}

		