

#BSUB -P atac_seq_f
#BSUB -o atac_seq_footprint_yli11_2020-07-24/log_files/diffFT_%J_%I.out -e atac_seq_footprint_yli11_2020-07-24/log_files/diffFT_%J_%I.err
#BSUB -n 1
#BSUB -q priority
#BSUB -R "span[hosts=1] rusage[mem=16000]"
#BSUB -J "diffFT[1-1]"

#BSUB -w "ended(107028078)"

module purge

id=$LSB_JOBINDEX
COL1=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1`

ncore=1
mem=16000
q=priority
module load conda3
source activate /home/yli11/.conda/envs/rgt_hint/
rgt-hint differential --organism=mm9 --bc --nc 10 --mpbs-files=./atac_seq_footprint_yli11_2020-07-24/None_motif_match/None_mpbs.bed,./atac_seq_footprint_yli11_2020-07-24/None_motif_match/None_mpbs.bed --reads-files=None,None --conditions=None,None --output-location=atac_seq_footprint_yli11_2020-07-24/Diff_footprints_None_None --output-profiles
cd Diff_footprints_None_None
mkdir temp_files
mv None*.txt temp_files
mv None*.txt temp_files

