

#BSUB -P chip_seq_single
#BSUB -o chip_seq_single_yli11_2020-09-12.BWA.message_%J_%I.out -e chip_seq_single_yli11_2020-09-12.BWA.message_%J_%I.err
#BSUB -n 6
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=6000]"
#BSUB -J "BWA[1-12]"
module purge
module load bwa/0.7.16a
module load samtools/1.7

id=$LSB_JOBINDEX
COL1=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id chip_seq_single_yli11_2020-09-12.bwa.input|tail -n1`

bwa mem -t 6 /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../mm9/bwa_16a_index/mm9.fa ${COL1} |samtools view -@ 6 -bS - > ${COL2}.bam

		