

#BSUB -P chip_seq_single
#BSUB -o chip_seq_single_yli11_2020-09-17.spp.message_%J_%I.out -e chip_seq_single_yli11_2020-09-17.spp.message_%J_%I.err
#BSUB -n 2
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=6000]"
#BSUB -J "spp[1-10]"
module purge
#BSUB -w "ended(109803376[*])"
module load R/3.4.0
module load samtools/1.7

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

Rscript /research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/../bin/run_spp.R -c=${COL2}.markdup.uq.bam -p=2 -savp -odir=. -rf > ${COL2}.spp.log

		