

#BSUB -P super_enhancer_yli11_2020-06-14
#BSUB -o super_enhancer_yli11_2020-06-14/log_files/SE_%J_%I.out -e super_enhancer_yli11_2020-06-14/log_files/SE_%J_%I.err
#BSUB -n 1
#BSUB -q priority
#BSUB -R "span[hosts=1] rusage[mem=8000]"
#BSUB -J "SE[1-2]"



module purge

id=$LSB_JOBINDEX
COL1=`head -n $id input2.list|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id input2.list|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id input2.list|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id input2.list|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id input2.list|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id input2.list|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id input2.list|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id input2.list|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id input2.list|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id input2.list|tail -n1`

ncore=1
mem=8000
q=priority
module load python/2.7.13 samtools/1.7 R/3.5.1
gff=${COL1}
bam=${COL2}
label=${COL3}
control=histone_input_HPC5_combined.markdup.bam
python ROSE_main.py -g mm9 -i $gff -c $control -r $bam -o $label
python ROSE_geneMapper.py -g mm9 -i $label/${label}_SuperEnhancers.table.txt -o $label

