

#BSUB -P chip_seq_single
#BSUB -o chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_%J_%I.out -e chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_%J_%I.err
#BSUB -n 6
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "rmdup[1-3]"
module purge
#BSUB -w "ended(105021396[*])"
module load samtools/1.7

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

samtools stats ${COL2}.bam > ${COL2}.bam.stat
samtools sort -@ 6 -n -o ${COL2}.name.st.bam ${COL2}.bam
samtools fixmate -@ 6 -m ${COL2}.name.st.bam ${COL2}.fixmate.bam
samtools sort -@ 6 -o ${COL2}.fixmate.st.bam ${COL2}.fixmate.bam
samtools markdup -@ 6 ${COL2}.fixmate.st.bam ${COL2}.markdup.bam
samtools markdup -@ 6 -r ${COL2}.markdup.bam ${COL2}.rmdup.bam
rm ${COL2}.name.st.bam ${COL2}.fixmate.bam ${COL2}.fixmate.st.bam
samtools flagstat -@ 6 ${COL2}.markdup.bam > ${COL2}.markdup.report
samtools index -@ 6 ${COL2}.markdup.bam
samtools view -@ 6 -q 1 -b ${COL2}.markdup.bam > ${COL2}.markdup.uq.bam
samtools index -@ 6 ${COL2}.markdup.uq.bam
samtools index -@ 6 ${COL2}.rmdup.bam
samtools view -@ 6 -q 1 -b ${COL2}.rmdup.bam > ${COL2}.rmdup.uq.bam
samtools index -@ 6 ${COL2}.rmdup.uq.bam
samtools view -@ 6 ${COL2}.markdup.bam chrM -b > ${COL2}.markdup.chrM.bam
samtools flagstat -@ 6 ${COL2}.markdup.chrM.bam > ${COL2}.markdup.chrM.report
samtools idxstats ${COL2}.rmdup.uq.bam | cut -f 1 | grep -v  chrM| xargs samtools view -@ 6 -b ${COL2}.rmdup.uq.bam > ${COL2}.rmdup.uq.rmchrM.bam
samtools idxstats ${COL2}.markdup.bam | cut -f 1 | grep -v  chrM| xargs samtools view -@ 6 -b ${COL2}.markdup.bam > ${COL2}.markdup.rmchrM.bam
samtools flagstat -@ 6 ${COL2}.markdup.rmchrM.bam > ${COL2}.markdup.rmchrM.report

		