

#BSUB -P chip_seq_single
#BSUB -o chip_seq_single_yli11_2020-06-08/log_files/chip_seq_single_yli11_2020-06-08.html.message_%J_%I.out -e chip_seq_single_yli11_2020-06-08/log_files/chip_seq_single_yli11_2020-06-08.html.message_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=8000]"
#BSUB -J "html[1-1]"
module purge
#BSUB -w "ended(105021395) && ended(105021398) && ended(105021397) && ended(105021396) && ended(105021404) && ended(105021402) && ended(105021400) && ended(105021403) && ended(105021401) && ended(105021399)"
module load python/2.7.13

id=$LSB_JOBINDEX
COL1=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id fastq.tsv|tail -n1|awk -F "	" '{print $6}'`
LINE=`head -n $id fastq.tsv|tail -n1`

/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/NGS.report.py chip_seq_single_yli11_2020-06-08 chip_seq_single histone_input_HPC5_combined.fastq.gz,1706666_MW127_H3K27ac.fastq.gz,1706665_MW127_H3K27ac.fastq.gz histone_input_HPC5_combined,1706666_MW127_H3K27ac,1706665_MW127_H3K27ac
/research/dept/hem/common/sequencing/chenggrp/pipelines/subcmd/send_email.py cf7d5e1d007f.bwDict
mkdir chip_seq_single_yli11_2020-06-08
mkdir chip_seq_single_yli11_2020-06-08/figures_tables
mv chip_seq_single_yli11_2020-06-08.report.html chip_seq_single_yli11_2020-06-08/figures_tables
mkdir chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.input chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.message_105021395_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.message_105021395_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.message_105021395_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.message_105021395_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.message_105021395_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.fastqc.message_105021395_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.bwa.input chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.message_105021396_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.message_105021396_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.message_105021396_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.message_105021396_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.message_105021396_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.BWA.message_105021396_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.mk.rm.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_105021397_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_105021397_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_105021397_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_105021397_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_105021397_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.markdup.rmdup.message_105021397_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.message_105021398_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.message_105021398_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.message_105021398_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.message_105021398_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.message_105021398_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.spp.message_105021398_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.message_105021399_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.message_105021399_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.message_105021399_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.message_105021399_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.message_105021399_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.all.bw.message_105021399_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.message_105021400_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.message_105021400_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.message_105021400_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.message_105021400_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.message_105021400_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.bw.message_105021400_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.message_105021401_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.message_105021401_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.message_105021401_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.message_105021401_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.message_105021401_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.rmdup.uq.bw.message_105021401_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.libx.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.lib.complexity.message_105021402_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.lib.complexity.message_105021402_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.lib.complexity.message_105021402_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.lib.complexity.message_105021402_2.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.lib.complexity.message_105021402_3.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.lib.complexity.message_105021402_3.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.macs2.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.macs2.message_105021403_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.macs2.message_105021403_1.err chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.macs2.message_105021403_2.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.macs2.message_105021403_2.err chip_seq_single_yli11_2020-06-08/log_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined*.r chip_seq_single_yli11_2020-06-08/log_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined*.r chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.tracks.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.tracks.message_105021404_1.out chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.tracks.message_105021404_1.err chip_seq_single_yli11_2020-06-08/log_files
mv cf7d5e1d007f.bwDict chip_seq_single_yli11_2020-06-08/log_files
mkdir chip_seq_single_yli11_2020-06-08/bw_files
mv histone_input_HPC5_combined.all.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.all.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.all.bw chip_seq_single_yli11_2020-06-08/bw_files
mv histone_input_HPC5_combined.rmdup.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.rmdup.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.rmdup.bw chip_seq_single_yli11_2020-06-08/bw_files
mv histone_input_HPC5_combined.rmdup.uq.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.rmdup.uq.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.rmdup.uq.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined_FE.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined_logLR.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined_treat_pvalue.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup.uq.rmchrM_FE.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup.uq.rmchrM_logLR.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup.uq.rmchrM_treat_pvalue.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup_FE.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup_logLR.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup_treat_pvalue.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined_FE.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined_logLR.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined_treat_pvalue.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup.uq.rmchrM_FE.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup.uq.rmchrM_logLR.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup.uq.rmchrM_treat_pvalue.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup_FE.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup_logLR.bw chip_seq_single_yli11_2020-06-08/bw_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined.rmdup_treat_pvalue.bw chip_seq_single_yli11_2020-06-08/bw_files
mkdir chip_seq_single_yli11_2020-06-08/peak_files
mv histone_input_HPC5_combined.markdup.uq.pdf chip_seq_single_yli11_2020-06-08/peak_files
mv histone_input_HPC5_combined.spp.log chip_seq_single_yli11_2020-06-08/peak_files
mv 1706666_MW127_H3K27ac.markdup.uq.pdf chip_seq_single_yli11_2020-06-08/peak_files
mv 1706666_MW127_H3K27ac.spp.log chip_seq_single_yli11_2020-06-08/peak_files
mv 1706665_MW127_H3K27ac.markdup.uq.pdf chip_seq_single_yli11_2020-06-08/peak_files
mv 1706665_MW127_H3K27ac.spp.log chip_seq_single_yli11_2020-06-08/peak_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined*.bed chip_seq_single_yli11_2020-06-08/peak_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined*.xls chip_seq_single_yli11_2020-06-08/peak_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined*narrowPeak* chip_seq_single_yli11_2020-06-08/peak_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined*.bed chip_seq_single_yli11_2020-06-08/peak_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined*.xls chip_seq_single_yli11_2020-06-08/peak_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined*narrowPeak* chip_seq_single_yli11_2020-06-08/peak_files
mkdir chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined_fastqc.html chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined_fastqc.zip chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac_fastqc.html chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac_fastqc.zip chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac_fastqc.html chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac_fastqc.zip chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined.markdup.report chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined.markdup.chrM.report chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined.bam.stat chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined.markdup.rmchrM.report chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac.markdup.report chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac.markdup.chrM.report chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac.bam.stat chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac.markdup.rmchrM.report chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac.markdup.report chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac.markdup.chrM.report chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac.bam.stat chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac.markdup.rmchrM.report chip_seq_single_yli11_2020-06-08/QC_files
mv histone_input_HPC5_combined.lib.complexity chip_seq_single_yli11_2020-06-08/QC_files
mv 1706666_MW127_H3K27ac.lib.complexity chip_seq_single_yli11_2020-06-08/QC_files
mv 1706665_MW127_H3K27ac.lib.complexity chip_seq_single_yli11_2020-06-08/QC_files
mkdir chip_seq_single_yli11_2020-06-08/bdg_files
mv 1706666_MW127_H3K27ac.vs.histone_input_HPC5_combined*.bdg chip_seq_single_yli11_2020-06-08/bdg_files
mv 1706665_MW127_H3K27ac.vs.histone_input_HPC5_combined*.bdg chip_seq_single_yli11_2020-06-08/bdg_files
mkdir chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.markdup.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.markdup.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.markdup.chrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.rmdup.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.rmdup.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.rmdup.uq.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.markdup.uq.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.rmdup.uq.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.markdup.uq.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.rmdup.uq.rmchrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv histone_input_HPC5_combined.markdup.rmchrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.markdup.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.markdup.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.markdup.chrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.rmdup.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.rmdup.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.rmdup.uq.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.markdup.uq.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.rmdup.uq.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.markdup.uq.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.rmdup.uq.rmchrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706666_MW127_H3K27ac.markdup.rmchrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.markdup.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.markdup.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.markdup.chrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.rmdup.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.rmdup.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.rmdup.uq.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.markdup.uq.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.rmdup.uq.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.markdup.uq.bam.bai chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.rmdup.uq.rmchrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv 1706665_MW127_H3K27ac.markdup.rmchrM.bam chip_seq_single_yli11_2020-06-08/bam_files
mv chip_seq_single_yli11_2020-06-08.html.lsf chip_seq_single_yli11_2020-06-08/log_files
mv chip_seq_single_yli11_2020-06-08.log chip_seq_single_yli11_2020-06-08/log_files
HemTools my_dir -a chip_seq_single_yli11_2020-06-08,/research/rgs01/home/clusterHome/yli11/Share/Megan/figures/chromHMM_input/H3K27ac_enhancer,chip_seq_single
module load conda3
source activate /home/yli11/.conda/envs/multiQC/
export LC_ALL=en_US.utf-8
export LANG=en_US.utf-8
cd chip_seq_single_yli11_2020-06-08
multiqc .

		