

#BSUB -P S3norm_yli
#BSUB -o S3norm_yli11_2021-10-09/log_files/email_%J_%I.out -e S3norm_yli11_2021-10-09/log_files/email_%J_%I.err
#BSUB -n 1
#BSUB -q standard
#BSUB -R "span[hosts=1] rusage[mem=4000]"
#BSUB -J "email[1-1]"

#BSUB -w "ended(142517553) && ended(142517554) && ended(142517555)"

module purge

id=$LSB_JOBINDEX
COL1=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $1}'`
COL2=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $2}'`
COL3=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $3}'`
COL4=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $4}'`
COL5=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $5}'`
COL6=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $6}'`
COL7=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $7}'`
COL8=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $8}'`
COL9=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1|awk -F "	" '{print $9}'`
LINE=`head -n $id /research/rgs01/home/clusterHome/yli11/HemTools/utils/../share/misc/sample.tsv|tail -n1`

echo ${COL1}
echo ${COL2}
echo ${COL3}
echo ${COL4}
echo ${COL5}
echo ${COL6}

module load python/2.7.13
mv -f S3norm_NBP_bedgraph S3norm_yli11_2021-10-09
mv -f S3norm_rc_bedgraph S3norm_yli11_2021-10-09
mv -f NBP_bedgraph S3norm_yli11_2021-10-09
mv -f average_ref_bedgraph S3norm_yli11_2021-10-09
cd S3norm_yli11_2021-10-09
send_email_v1.py -m "S3norm_yli11_2021-10-09 is finished" -j S3norm_yli11_2021-10-09

